<?php

/**
 * Laika PHP MVC Framework
 * Author: Showket Ahmed
 * Email: riyadhtayf@gmail.com
 * License: MIT
 * This file is part of the Laika PHP MVC Framework.
 * For the full copyright and license information, please view the LICENSE file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Laika\Core\App;

// Deny Direct Access
if (php_sapi_name() !== 'cli' && !defined('APP_PATH')) {
    http_response_code(403);
    exit('Direct Access Denied!');
}

use Twig\{Loader\FilesystemLoader as Engine, Environment, TwigFilter};
use Laika\Core\Directory;
use Laika\Core\Local;
use Laika\Core\File;

class Template
{
    /**
     * @var object $twig
     */
    protected object $twig;

    /**
     * @var array $vars
     */
    protected array $vars = [];

    /**
     * @var ?string $templateDirectory Template Directory
     */
    protected ?string $templateDirectory;

    /**
     * @var ?string $cacheDirectory Template Cache Directory
     */
    protected ?string $cacheDirectory;

    public function __construct(?string $templateSubDirectory = null, ?string $cacheSubDirectory = null)
    {
        // Ensure Template & Cache Paths
        $this->ensureTemplatePath($templateSubDirectory);
        $this->ensureCachePath($cacheSubDirectory);

        // Run Template Engine
        $engine = new Engine($this->templateDirectory);
        $this->twig = new Environment($engine, [
            'debug' =>  option('debug', false),
            'cache' =>  $this->cacheDirectory
        ]);

        // Assign Template Default Vars & Filters
        $this->assign('app', Env::get('app|info'));
        $this->assign('local', Local::get());
        $this->addFilter('hook', 'do_hook');
        $this->addFilter('named', function(string $name, array $params = []){
            return named($name, $params, true);
        });

        // Load Template Hook Path if Exists
        $file = new File("{$this->templateDirectory}/hooks.php");
        if (!$file->exists()) {
            $file->touch();
            $file->write("<?php\n\n// Auto Generated By Application\n\n");
        }

        $file->require(true);
    }

    public function view(string $name): string
    {
        return $this->twig->render("{$name}.twig", $this->vars);
    }

    /**
     * Assign Variable
     * @param string|array $key Key Name or Array of Key, Value Pair
     * @param mixed $value Key Name or Array of Key, Value Pair
     */
    public function assign(string|array $key, mixed $value = null): void
    {
        if (is_string($key)) {
            $key = [$key => $value];
        }
        $this->vars = array_merge($this->vars, $key);
    }

    public function addFilter(string $name, $callable): void
    {
        $this->twig->addFilter(new TwigFilter($name, $callable));
    }

    #################################################################################
    /*-------------------------------- PRIVATE API --------------------------------*/
    #################################################################################

    // Ensure Template Path
    private function ensureTemplatePath(?string $subdir = null): void
    {
        $subdir = $subdir ? trim($subdir, '/') : '';
        $this->templateDirectory = is_dir($subdir) ? $subdir : APP_PATH . "/lf-templates/{$subdir}";
        $this->templateDirectory = rtrim($this->templateDirectory, '/');
        Directory::make($this->templateDirectory);
    }

    // Ensure Template Path
    private function ensureCachePath(?string $subdir = null): void
    {
        $subdir = $subdir ? trim($subdir, '/') : '';
        $this->cacheDirectory = is_dir($subdir) ? $subdir : APP_PATH . "/lf-cache/{$subdir}";
        $this->cacheDirectory = rtrim($this->cacheDirectory, '/');
        Directory::make($this->cacheDirectory);
    }
}
